# Generated by Django 3.2.9 on 2021-11-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepie',
            name='lines',
        ),
        migrations.AddField(
            model_name='recepieline',
            name='recepie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.recepie'),
        ),
    ]
