# Generated by Django 3.2.9 on 2022-01-08 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211121_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='serving',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serving', to='api.servingsize'),
        ),
    ]
